# syntax=docker/dockerfile:1

FROM node:22-bookworm-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV CI=true
ENV DEBIAN_FRONTEND=noninteractive

RUN corepack enable && corepack prepare pnpm@9.15.9 --activate

WORKDIR /app

CMD ["pnpm", "dev"]
